export const PACKAGES = [
  {
    id: 'ultimate',
    name: 'Ultimate Adventure Day',
    price: 1500,
    category: 'Day Trips',
    description: 'Hike, explore and experience the best of the Western Cape in one action-packed day.',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600',
  },
  {
    id: 'family',
    name: 'Family Explorer Package',
    price: 1500,
    category: 'Weekend',
    description: 'Perfect for families looking for fun and safe adventure.',
    image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600',
  },
  {
    id: 'weekend',
    name: 'Weekend Explorer',
    price: 1500,
    category: 'Weekend',
    description: 'Two days of hiking, kayaking and exploring the outdoors.',
    image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600',
  },
  {
    id: 'group',
    name: 'Group Adventure Package',
    price: 1500,
    category: 'Group',
    description: 'Custom packages for groups, corporate events and team building.',
    image: 'https://images.unsplash.com/photo-1533240332313-0db49b459ad6?w=600',
  },
];

export const ACTIVITIES = [
  {
    id: 'ziplining',
    name: 'Ziplining',
    price: 750,
    rating: 4.8,
    reviews: 124,
    category: 'Adventure',
    difficulty: 'Moderate',
    duration: '2 - 3 Hours',
    age: '8+ Years',
    description:
      'Experience the thrill of ziplining across breathtaking valleys and natural landscapes. Perfect for adventure seekers and nature lovers.',
    image: 'https://images.unsplash.com/photo-1622396636133-ac6e9dfd4ac0?w=600',
  },
  {
    id: 'kayaking',
    name: 'Kayaking',
    price: 750,
    rating: 4.7,
    reviews: 98,
    category: 'Water',
    difficulty: 'Moderate',
    duration: '2 - 3 Hours',
    age: '10+ Years',
    description: 'Explore pristine waters and coastal views by kayak, guided by experienced instructors.',
    image: 'https://images.unsplash.com/photo-1520383278413-e0602ee9b3a3?w=600',
  },
  {
    id: 'rockclimbing',
    name: 'Rock Climbing',
    price: 750,
    rating: 4.9,
    reviews: 76,
    category: 'Land',
    difficulty: 'Challenging',
    duration: '3 Hours',
    age: '12+ Years',
    description: 'Challenge yourself with stunning views on a guided rock climbing route.',
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600',
  },
];